"""
Computes @font-face override values so the fallback font occupies exactly the
same space as the webfont it stands in for.

Why this exists: with `font-display: swap` the browser paints text immediately
in a fallback, then swaps when the real font arrives. If the two have different
metrics, everything below the swapped text jumps — which is what took CLS from
0 to 0.114 the moment the fonts became self-hosted and fast enough to paint
before they landed.

The overrides make the stand-in a dimensional twin of the real thing:

  size-adjust        scales the fallback so its average character is the same
                     width, which is what stops lines re-wrapping
  ascent-override    fixes the space above the baseline
  descent-override   the space below it
  line-gap-override  the leading between lines

Run: python scripts/font-metrics.py
Then paste the printed rules into src/lib/styles/global.css.
"""

import sys
from fontTools.ttLib import TTFont

WIN = 'C:/Windows/Fonts/'

# Each webfont, and the font actually standing in for it while it loads — which
# must be the first entry in that stack's fallback list, or the numbers describe
# a font nobody sees. Arial's metrics are shared by Helvetica and Liberation
# Sans, so one calculation covers macOS and Linux too.
PAIRS = [
    ('Newsreader', 'src/lib/fonts/newsreader-400.woff2', WIN + 'georgia.ttf', 'Georgia'),
    ('Lato', 'src/lib/fonts/lato-400.woff2', WIN + 'arial.ttf', 'Arial'),
    ('JetBrains Mono', 'src/lib/fonts/jetbrains-mono-400.woff2', WIN + 'cour.ttf', 'Courier New'),
]

# Weighted by how often each letter appears in English, so the average width
# reflects real prose rather than treating 'z' as equal to 'e'.
FREQ = {
    'a': 8.17, 'b': 1.49, 'c': 2.78, 'd': 4.25, 'e': 12.70, 'f': 2.23, 'g': 2.02,
    'h': 6.09, 'i': 6.97, 'j': 0.15, 'k': 0.77, 'l': 4.03, 'm': 2.41, 'n': 6.75,
    'o': 7.51, 'p': 1.93, 'q': 0.10, 'r': 5.99, 's': 6.33, 't': 9.06, 'u': 2.76,
    'v': 0.98, 'w': 2.36, 'x': 0.15, 'y': 1.97, 'z': 0.07, ' ': 17.0,
}


def avg_width(font):
    """Frequency-weighted mean advance width, in em units."""
    upem = font['head'].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font['hmtx']
    total = weight = 0.0
    for ch, f in FREQ.items():
        name = cmap.get(ord(ch))
        if not name:
            continue
        total += hmtx[name][0] / upem * f
        weight += f
    return total / weight


print('/* Generated by scripts/font-metrics.py — see that file for the why. */')
for family, real_path, fb_path, fb_name in PAIRS:
    try:
        real = TTFont(real_path)
        fb = TTFont(fb_path)
    except Exception as e:  # noqa: BLE001
        print(f'/* skipped {family}: {e} */', file=sys.stderr)
        continue

    adjust = avg_width(real) / avg_width(fb)

    upem = real['head'].unitsPerEm
    hhea = real['hhea']
    # Divided by the size adjustment because the overrides are applied to the
    # already-scaled fallback, not to the original.
    asc = hhea.ascent / upem / adjust
    desc = abs(hhea.descent) / upem / adjust
    gap = hhea.lineGap / upem / adjust

    print(f"""
@font-face {{
	font-family: '{family} Fallback';
	src: local('{fb_name}');
	size-adjust: {adjust * 100:.2f}%;
	ascent-override: {asc * 100:.2f}%;
	descent-override: {desc * 100:.2f}%;
	line-gap-override: {gap * 100:.2f}%;
}}""")
