/**
 * Writes src/lib/data/image-sizes.json: the real pixel dimensions of every
 * image variant the site can serve.
 *
 * Why a manifest rather than width and height typed into each tag: almost every
 * <img> on this site has a dynamic src. The bird library renders one tag for
 * 132 species, the tour cards one for ten tours. There is no static answer to
 * "how big is this image" at the tag, only at the file.
 *
 * Only `full`, `md` and `portrait` are stored. The other three variants are
 * fixed crops by construction, so storing 160 copies of "800x600" would be 160
 * chances for the file to disagree with the generator.
 *
 * Run: node scripts/image-sizes.mjs   (after adding or replacing images)
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const IMG = join(root, 'static', 'images');
const OUT = join(root, 'src', 'lib', 'data', 'image-sizes.json');

/** Variants whose shape is decided by the crop, not by the source. */
const FIXED = { card: [800, 600], sq: [600, 600], thumb: [420, 420] };
const MEASURED = ['full', 'md', 'portrait'];

const sizes = {};
let measured = 0;

for (const file of readdirSync(IMG).sort()) {
	const m = file.match(/^(.*)-(full|md|portrait)\.webp$/);
	if (!m) continue;
	const [, stem, variant] = m;
	const { width, height } = await sharp(join(IMG, file)).metadata();
	(sizes[stem] ??= {})[variant] = [width, height];
	measured++;
}

const out = {
	_note:
		'Generated by scripts/image-sizes.mjs. card, sq and thumb are fixed crops and are not stored.',
	fixed: FIXED,
	sizes
};

writeFileSync(OUT, JSON.stringify(out, null, '\t') + '\n');
console.log(
	`image-sizes: ${measured} variants across ${Object.keys(sizes).length} images -> ${(
		JSON.stringify(out).length / 1024
	).toFixed(0)}KB`
);
console.log(`image-sizes: variants measured ${MEASURED.join(', ')}; fixed ${Object.keys(FIXED).join(', ')}`);
